version: 2.1
jobs:
  build:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Connect to Docker Hub
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - restore_cache:
          keys:
            - v1-last-build-{{ .Branch }}
          paths:
            - .last-build-version
      - run:
          name: Build images
          command: |
            build/container release --push
      - save_cache:
          key: v1-last-build-{{ .Branch }}
          paths:
            - .last-build-version

# workflow for this project
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: build
